name: Deploy to GitHub Pages

on:
  push:
    branches: [ main, 4-tidy-up-ui ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Verify project structure
        run: |
          echo "Project structure:"
          ls -la
          echo "Static files:"
          ls -la static/ || echo "No static directory"

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Build site
        run: |
          # Create dist directory for GitHub Pages
          mkdir -p dist
          
          # Copy all necessary files to dist
          cp ni-map.html dist/index.html
          cp -r static dist/ 2>/dev/null || echo "No static directory to copy"
          
          # Create a simple fallback index if needed
          if [ ! -f dist/index.html ]; then
            echo "Creating fallback index.html"
            cp index.html dist/ 2>/dev/null || echo "<!DOCTYPE html><html><head><title>Northern Ireland Map</title></head><body><h1>Map Application</h1><p>Please check the deployment configuration.</p></body></html>" > dist/index.html
          fi
          
          echo "Build complete. Contents of dist:"
          ls -la dist/

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/4-tidy-up-ui'
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
